drop table document_lines;
drop table documents;
drop table projects;
drop table users;
drop table clients;

CREATE TABLE clients (
CLIENT_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
STREET VARCHAR(50) NOT NULL,
POST_CODE VARCHAR(5) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PHONE_NUMBER VARCHAR(30),
MAIL VARCHAR(30),
TAX_NUMBER VARCHAR(30)
)
ENGINE=InnoDB;

CREATE TABLE users(
USERNAME VARCHAR(20) PRIMARY KEY  NOT NULL,
PASSWORD VARCHAR(60) NOT NULL
)
ENGINE=InnoDB;

insert into users values('admin', '$2a$10$lqa.0P8bsTPgbWLMYGc16O9C/q//yGbXuWKibgFBMzmY9s3ZrOaWq');

CREATE TABLE projects(
PROJECT_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
DESCRIPTION VARCHAR(50) NOT NULL,
STREET VARCHAR(30) NOT NULL,
POST_CODE VARCHAR(5) NOT NULL,
CITY VARCHAR(30) NOT NULL,
START_DATE DATE NOT NULL,
END_DATE DATE NOT NULL,
CLIENT_ID INT(10) NOT NULL,
constraint FK_PROJECTS_CLIENTS foreign key(CLIENT_ID) references clients(CLIENT_ID) ON DELETE CASCADE
)
ENGINE=InnoDB;

CREATE TABLE documents(
DOCUMENT_ID INT(10) PRIMARY KEY NOT NULL,
CREATION_DATE DATE NOT NULL,
PAYMENT_DATE DATE NOT NULL,
TAX_RATE BIGINT NOT NULL,
CLIENT_ID INT(10) NOT NULL,
PROJECT_ID INT(10) NOT NULL,
constraint FK_DOCUMENTS_CLIENTS foreign key(CLIENT_ID) references clients(CLIENT_ID) ON DELETE CASCADE,
constraint FK_DOCUMENTS_PROJECTS foreign key(PROJECT_ID) references projects(PROJECT_ID) ON DELETE CASCADE
)
ENGINE=InnoDB;

CREATE TABLE document_lines(
DOCUMENT_LINE_ID VARCHAR(10) PRIMARY KEY NOT NULL,
PRICE BIGINT NOT NULL,
QUANTITY BIGINT NOT NULL,
UNIT VARCHAR(5) NOT NULL,
DOCUMENT_ID INT(10) NOT NULL,
constraint FK_DOCUMENTS_LINES_DOCUMENTS foreign key(DOCUMENT_ID) references documents(DOCUMENT_ID) ON DELETE CASCADE
)
ENGINE=InnoDB;