CREATE TABLE clients (
CLIENT_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
STREET VARCHAR(50) NOT NULL,
POST_CODE VARCHAR(5) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PHONE_NUMBER VARCHAR(30),
MAIL VARCHAR(30),
TAX_NUMBER VARCHAR(30)
)
ENGINE = InnoDB;

CREATE TABLE users(
USERNAME VARCHAR(20) PRIMARY KEY  NOT NULL,
PASSWORD VARCHAR(60) NOT NULL
)
ENGINE = InnoDB;

insert into users values('admin', '$2a$10$lqa.0P8bsTPgbWLMYGc16O9C/q//yGbXuWKibgFBMzmY9s3ZrOaWq');

CREATE TABLE services(
SERVICE_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
  TYPE VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(50),
STREET VARCHAR(30),
POST_CODE VARCHAR(5),
CITY VARCHAR(30),
START_DATE DATE,
END_DATE DATE ,
CLIENT_ID INT(10) NOT NULL,
constraint FK_PROJECTS_CLIENTS foreign key(CLIENT_ID) references clients(CLIENT_ID) ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE documents(
DOCUMENT_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
DOCUMENT_CODE VARCHAR(10) NOT NULL,
TYPE VARCHAR(10) NOT NULL,
CREATION_DATE DATE NOT NULL,
PAYMENT_DATE DATE NOT NULL,
TAX_RATE DECIMAL(3,2) NOT NULL,
CLIENT_ID INT(10) NOT NULL,
SERVICE_ID INT(10) NOT NULL,
constraint FK_DOCUMENTS_CLIENTS foreign key(CLIENT_ID) references clients(CLIENT_ID) ON DELETE CASCADE,
constraint FK_DOCUMENTS_PROJECTS foreign key(SERVICE_ID) references services(SERVICE_ID) ON DELETE CASCADE
)
ENGINE = InnoDB;

CREATE TABLE document_lines(
DOCUMENT_LINE_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
DESCRIPTION VARCHAR(100) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL,
QUANTITY DECIMAL(10,2) NOT NULL,
UNIT VARCHAR(5) NOT NULL,
DOCUMENT_ID INT(10) NOT NULL,
constraint FK_DOCUMENTS_LINES_DOCUMENTS foreign key(DOCUMENT_ID) references documents(DOCUMENT_ID) ON DELETE CASCADE
)
ENGINE = InnoDB;