CREATE TABLE clients (
  CLIENT_ID    INT(10) PRIMARY KEY auto_increment NOT NULL,
  LAST_NAME    VARCHAR(60) NOT NULL,
  FIRST_NAME   VARCHAR(30),
  STREET       VARCHAR(50) NOT NULL,
  POST_CODE    VARCHAR(5)  NOT NULL,
  CITY         VARCHAR(30) NOT NULL,
  PHONE_NUMBER VARCHAR(30),
  MAIL         VARCHAR(30),
  TAX_NUMBER   VARCHAR(30)
)
  ENGINE = InnoDB;


CREATE TABLE users (
  USERNAME VARCHAR(20) PRIMARY KEY  NOT NULL,
  PASSWORD VARCHAR(60)              NOT NULL,
  ENABLED  BOOLEAN                  NOT NULL
)
  ENGINE = InnoDB;

create table authorities (
  USERNAME  VARCHAR(20) NOT NULL,
  AUTHORITY VARCHAR(20) NOT NULL,
  CONSTRAINT fk_authorities_users FOREIGN KEY (USERNAME) REFERENCES users (USERNAME)
)
  ENGINE = InnoDB;

insert into users
values ('admin', '$2a$10$lqa.0P8bsTPgbWLMYGc16O9C/q//yGbXuWKibgFBMzmY9s3ZrOaWq', true);
insert into authorities
values ('admin', 'ADMIN');

CREATE TABLE projects (
  PROJECT_ID  INT(10) PRIMARY KEY auto_increment NOT NULL,
  DESCRIPTION VARCHAR(50),
  STREET      VARCHAR(30),
  POST_CODE   VARCHAR(5),
  CITY        VARCHAR(30),
  START_DATE  DATE,
  END_DATE    DATE,
  CLIENT_ID   INT(10) NOT NULL,
  constraint FK_PROJECTS_CLIENTS foreign key (CLIENT_ID) references clients (CLIENT_ID) ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE TABLE documents (
  DOCUMENT_ID   INT(10) PRIMARY KEY auto_increment NOT NULL,
  DOCUMENT_CODE VARCHAR(10) NOT NULL,
  TYPE          VARCHAR(15) NOT NULL,
  CREATION_DATE DATE        NOT NULL,
  PAYMENT_DATE  DATE,
  TAX_RATE      VARCHAR(5)  NOT NULL,
  CLIENT_ID     INT(10)     NOT NULL,
  PROJECT_ID    INT(10),
  constraint FK_DOCUMENTS_CLIENTS foreign key (CLIENT_ID) references clients (CLIENT_ID) ON DELETE CASCADE,
  constraint FK_DOCUMENTS_PROJECTS foreign key (PROJECT_ID) references projects (PROJECT_ID) ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE TABLE document_lines (
  DOCUMENT_LINE_ID INT(10) PRIMARY KEY auto_increment NOT NULL,
  DESCRIPTION      VARCHAR(200)   NOT NULL,
  PRICE            DECIMAL(10, 2) NOT NULL,
  QUANTITY         DECIMAL(10, 3) NOT NULL,
  UNIT             VARCHAR(5)     NOT NULL,
  DOCUMENT_ID      INT(10),
  constraint FK_DOCUMENTS_LINES_DOCUMENTS foreign key (DOCUMENT_ID) references documents (DOCUMENT_ID) ON DELETE CASCADE
)
  ENGINE = InnoDB;